const translations = {
  en: {
    nav_home: 'Home',
    nav_learning: 'Learning',
    nav_scholarships: 'Scholarships',
    nav_mentoring: 'Mentoring',
    nav_speech: 'Speech Therapy',
    nav_mental_health: 'Mental Health',
    nav_study_plan: 'Study Plan',
    btn_login: 'Login',
    btn_register: 'Register',
    btn_get_started: 'Get Started',
    hero_title: 'Education for Every Indian Student',
    hero_subtitle:
      'Access quality learning, scholarships, mentoring, and wellness tools — in your own language. Built for rural India.',
  },
  ta: {
    nav_home: 'முகப்பு',
    nav_learning: 'கற்றல்',
    nav_scholarships: 'உதவித்தொகை',
    nav_mentoring: 'வழிகாட்டல்',
    nav_speech: 'பேச்சு சிகிச்சை',
    nav_mental_health: 'மன நலம்',
    nav_study_plan: 'படிப்பு திட்டம்',
    btn_login: 'உள்நுழை',
    btn_register: 'பதிவு செய்',
    btn_get_started: 'தொடங்கு',
    hero_title: 'ஒவ்வொரு இந்திய மாணவருக்கும் கல்வி',
    hero_subtitle:
      'உங்கள் மொழியில் தரமான கற்றல், உதவித்தொகை, வழிகாட்டல் மற்றும் நல்வாழ்வு கருவிகளை அணுகவும். கிராமப்புற இந்தியாவுக்காக உருவாக்கப்பட்டது.',
  },
  hi: {
    nav_home: 'होम',
    nav_learning: 'शिक्षा',
    nav_scholarships: 'छात्रवृत्ति',
    nav_mentoring: 'मार्गदर्शन',
    nav_speech: 'वाक् चिकित्सा',
    nav_mental_health: 'मानसिक स्वास्थ्य',
    nav_study_plan: 'अध्ययन योजना',
    btn_login: 'लॉगिन',
    btn_register: 'पंजीकरण',
    btn_get_started: 'शुरू करें',
    hero_title: 'हर भारतीय छात्र के लिए शिक्षा',
    hero_subtitle:
      'अपनी भाषा में गुणवत्तापूर्ण शिक्षा, छात्रवृत्ति, मार्गदर्शन और कल्याण उपकरण प्राप्त करें। ग्रामीण भारत के लिए बनाया गया।',
  },
  te: {
    nav_home: 'హోమ్',
    nav_learning: 'అభ్యాసం',
    nav_scholarships: 'స్కాలర్‌షిప్‌లు',
    nav_mentoring: 'మెంటరింగ్',
    nav_speech: 'స్పీచ్ థెరపీ',
    nav_mental_health: 'మానసిక ఆరోగ్యం',
    nav_study_plan: 'అధ్యయన ప్రణాళిక',
    btn_login: 'లాగిన్',
    btn_register: 'నమోదు',
    btn_get_started: 'ప్రారంభించండి',
    hero_title: 'ప్రతి భారతీయ విద్యార్థికి విద్య',
    hero_subtitle:
      'మీ భాషలో నాణ్యమైన అభ్యాసం, స్కాలర్‌షిప్‌లు, మెంటరింగ్ మరియు సంక్షేమ సాధనాలను యాక్సెస్ చేయండి. గ్రామీణ భారతదేశం కోసం నిర్మించబడింది.',
  },
  kn: {
    nav_home: 'ಮುಖಪುಟ',
    nav_learning: 'ಕಲಿಕೆ',
    nav_scholarships: 'ವಿದ್ಯಾರ್ಥಿವೇತನ',
    nav_mentoring: 'ಮಾರ್ಗದರ್ಶನ',
    nav_speech: 'ಮಾತು ಚಿಕಿತ್ಸೆ',
    nav_mental_health: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ',
    nav_study_plan: 'ಅಧ್ಯಯನ ಯೋಜನೆ',
    btn_login: 'ಲಾಗಿನ್',
    btn_register: 'ನೋಂದಣಿ',
    btn_get_started: 'ಪ್ರಾರಂಭಿಸಿ',
    hero_title: 'ಪ್ರತಿ ಭಾರತೀಯ ವಿದ್ಯಾರ್ಥಿಗೆ ಶಿಕ್ಷಣ',
    hero_subtitle:
      'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಗುಣಮಟ್ಟದ ಕಲಿಕೆ, ವಿದ್ಯಾರ್ಥಿವೇತನ, ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಕ್ಷೇಮ ಸಾಧನಗಳನ್ನು ಪ್ರವೇಶಿಸಿ. ಗ್ರಾಮೀಣ ಭಾರತಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
  },
  ml: {
    nav_home: 'ഹോം',
    nav_learning: 'പഠനം',
    nav_scholarships: 'സ്കോളർഷിപ്പുകൾ',
    nav_mentoring: 'മെന്ററിങ്',
    nav_speech: 'സ്പീച്ച് തെറാപ്പി',
    nav_mental_health: 'മാനസികാരോഗ്യം',
    nav_study_plan: 'പഠന പദ്ധതി',
    btn_login: 'ലോഗിൻ',
    btn_register: 'രജിസ്റ്റർ',
    btn_get_started: 'ആരംഭിക്കുക',
    hero_title: 'എല്ലാ ഇന്ത്യൻ വിദ്യാർത്ഥികൾക്കും വിദ്യാഭ്യാസം',
    hero_subtitle:
      'നിങ്ങളുടെ ഭാഷയിൽ ഗുണനിലവാരമുള്ള പഠനം, സ്കോളർഷിപ്പുകൾ, മെന്ററിങ്, ക്ഷേമ ഉപകരണങ്ങൾ എന്നിവ ആക്സസ് ചെയ്യുക. ഗ്രാമീണ ഇന്ത്യയ്ക്കായി നിർമ്മിച്ചത്.',
  },
};

export default translations;
